### ISSUE TITLE
Error always happens on exit

### ISSUE THREAD

**Issue by rubikonx9** [anufrievroman/calcure#107]
Whenever I quit `calcure`, it always prints out an error:

```
$ calcure
Traceback (most recent call last):
  File "/usr/sbin/calcure", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/calcure/__main__.py", line 1090, in cli
    curses.wrapper(main)
  File "/usr/lib/python3.12/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR
```

I have version `3.0.1-1` installed from AUR (Arch).

**Comment by anufrievroman** [comment]
I think this one was already fixed but the AUR maintainer didn't update the package yet. You can install the latest with `pipx install calcure`

**Comment by rubikonx9** [comment]
Right, it's marked as `[Out-of-date: 2024-07-09]`, I didn't notice.
I'll check later.
