### ISSUE TITLE
Issue with weather

### ISSUE THREAD

**Issue by luigir-it** [anufrievroman/calcure#31]
calcure.configuration doesn't have a MSG_WEATHER attribute, so the app fails to launch. 

`Traceback (most recent call last):
  File "/home/luigi/.local/bin/calcure", line 8, in <module>
    sys.exit(cli())
  File "/home/luigi/.local/lib/python3.10/site-packages/calcure/__main__.py", line 1029, in cli
    curses.wrapper(main)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/luigi/.local/lib/python3.10/site-packages/calcure/__main__.py", line 918, in main
    print(cf.MSG_WEATHER)
AttributeError: 'Config' object has no attribute 'MSG_WEATHER'. Did you mean: 'SHOW_WEATHER'?`

**Comment by anufrievroman** [comment]
Thank you for reporting! I just fixed this in version 2.5.4. Please update `pip install calcure --upgrade`.
