### ISSUE TITLE
Logging setup fails for Python v3.8.10

### ISSUE THREAD

**Issue by LanHikari22** [anufrievroman/calcure#52]
My workaround for this was to edit calcure/configurations.py and comment out encoding='utf-8' or the application would not start. I am not sure if this application does not support v3.8.10? The application seems to work okay.

Error:
Traceback (most recent call last):
  File "/home/lan/.local/bin/calcure", line 5, in <module>
    from calcure.__main__ import cli
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 13, in <module>
    from calcure.configuration import cf
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/configuration.py", line 352, in <module>
    logging.basicConfig(level=logging.INFO,
  File "/usr/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

**Comment by anufrievroman** [comment]
Interesting. I didn't know this argument was not supported in earlier versions. I commented out that line for now, like you suggested, that encoding is not so important actually, maybe it's okay without it. In version 2.8.5 it should be fixed then.
